version: '3.7'

services:
  issabel:
    image: deathmetall/issabel:live
    restart: always
    container_name: pbx_issabel
    networks:
      macvln0:
        ipv4_address: 172.22.0.21 # Asignación de la dirección IP especificada
    cap_add: 
      - NET_ADMIN
    privileged: true
    hostname: pbx.example
    mac_address: "00:60:2F:8B:57:91" # Dirección MAC especificada
    ports:
      - "25"     # SMTPS - mostly processing incoming mails
      - "465"    # SMTPS - mostly processing incoming mails
      - "89"     # HTTP - redirect to https (see options) and authentication for Let's encrypt service
      - "110"    # POP3 - standard protocol for accessing mailbox, STARTTLS is required before client auth
      - "143"    # IMAP - standard protocol for accessing mailbox, STARTTLS is required before client auth
      - "8433"   # HTTPS - access to administration or webmail client
      - "587"    # MSA - SMTP port used primarily for email clients after STARTTLS and auth
      - "993"    # IMAPS - alternative port for IMAP encrypted since connection
      - "995"    # POP3S - encrypted POP3 since connections
      - "5038"   # ASTERISK - puerto usado por asterisk SIP/IAX2
      - "5060/tcp"  # SIP - puerto SIP
      - "5060/udp"  # SIP - puerto SIP
      - "5061/udp"  # SIP - puerto SIP
      - "5061/tcp"  # SIP - puerto SIP
      - "8001"
      - "8003"
      - "8088"
      - "8089"
      - "9900/tcp"
      - "9900/udp"
      - "10000-10100/tcp"
      - "10000-10100/udp"

    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "issabel-etc:/etc"
      - "issabel-data:/var/lib"
      - "./httpd.conf:/etc/httpd/conf/httpd.conf"
      - "./ssl.conf:/etc/httpd/conf.d/ssl.conf"

networks:
  macvln0:
    external: true
    name: macvln0
    
volumes:
  issabel-etc:
  issabel-data:
